image: maven:3.6.1

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn clean package
        artifacts:
          - target/*
    - step:
        name: "Deploy to Production"
        # Track production environments builds using deployments.
        deployment: production
        caches:
          - maven
        script:
        - pipe: atlassian/aws-elasticbeanstalk-deploy:0.6.6
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            APPLICATION_NAME: "flur-jewellery"
            ENVIRONMENT_NAME: 'production'
            ZIP_FILE: "target/flur-jewellery-$version.jar"