image: node:12.14.1
definitions:
  steps:
    - step: &yarn
        name: Install Deps
        caches:
         - node # includes node_modules
        script:
          - yarn
    - step: &lint
        name: Lint Themes
        caches:
         - node
        script:
          - yarn lint
    - step: &build-and-deploy
        name: Build & Deploy
        deployment: development
        caches:
         - node
        script:
          - apt-get update
          - apt-get install zip
          - yarn build
          - zip -r application.zip . -x node_modules/\* src/\* .git/\*
        artifacts: 
            - application.zip
pipelines:
  branches:
    develop:
      - step: *yarn
      - step: *lint
    # Auto deploy to production on merge to master   
    master:
      - step: *build
      - step:
          name: Deploy to LIVE
          trigger: manual  # Uncomment to make this a manual deployment.
          script:
              - echo "Deploying to production environment"
              - pipe: atlassian/aws-elasticbeanstalk-deploy:0.7.0
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  APPLICATION_NAME: 'flur-jewellery'
                  ENVIRONMENT_NAME: 'production'
                  ZIP_FILE: 'application.zip'