image: node:12.14.1
definitions:
  steps:
    - step: &install-deps
        name: Install Deps
        caches:
         - node # includes node_modules
        script:
          - yarn
    - step: &lint
        name: Lint Code
        caches:
         - node
        script:
          - yarn lint
    - step: &build
        name: Build
        caches:
         - node
        script:
          - apt-get update
          - apt-get install zip
          - yarn build
          - zip -r application.zip . -x node_modules/\* src/\* .git/\*
        artifacts: 
            - application.zip
pipelines:
  branches:
    develop:
      - step: *install-deps
      - step: *lint
    # Auto deploy to production on merge to master   
    master:
      - step: *install-deps
      - step: *lint
      - step: *build
      - step:
          name: Deploy to LIVE
          # trigger: manual  # Uncomment to make this a manual deployment.
          script:
              - echo "Deploying to production environment"
              - pipe: atlassian/aws-elasticbeanstalk-deploy:0.7.0
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  APPLICATION_NAME: 'flur-api'
                  ENVIRONMENT_NAME: 'Flurapi-env-2'
                  ZIP_FILE: 'application.zip'
                  S3_BUCKET: $S3_BUCKET